teams:
  red:
    color: "&c"
    maximum_members: 10
    entity:
      location: world; 0, 100, 0, 0, 0
      health: 1000
      last_health: 1000 # EZT NE ÍRD ÁT! (csak ha akarod)
      name: "&cTúsz"
